### ISSUE TITLE
Song titles are not visible

### ISSUE THREAD

**Issue by J4CKED** [dracula/bandcamp#6]
Hi. I would like to report a bug. The song titles are not visible.
After turning off the script, the title is visible in the indicated place.

By the way, thank you for your work.

Example link: https://daily.bandcamp.com/best-experimental/the-best-experimental-music-on-bandcamp-april-2023

![dracula](https://user-images.githubusercontent.com/60573158/236015466-595f6ff5-d966-46b0-be9f-119f8b1db0f1.jpg)

**Comment by eros404** [comment]
Hi !

You are right, thank you for the report.
